# Generated by Django 5.1.5 on 2025-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('url', models.URLField()),
                ('inspection_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unsafe', 'Unsafe'), ('safe', 'Safe')], default='safe', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'url_inspection',
            },
        ),
    ]
