# Generated by Django 5.1.5 on 2025-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_deleted_at_profile_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('user', 'USER')], default='user', max_length=20, null=True),
        ),
    ]
