# Generated by Django 5.1.5 on 2025-03-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
